baseurl = "https://fubarhouse.github.io/blog/"
DefaultContentLanguage = "en"
title = "Karl's Blog"
#DefaultContentLanguage = "ja"
theme = "hugo-notepadium"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = true
pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
publishDir = "blog"

[Params]
  homeTitle = "Karl's Blog"
  subtitle = ""
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = false
  readingTime = true
  useHLJS = true
  socialShare = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "blog/img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "blog/img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "blog/img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Karl Hepworth"
  website = "yourwebsite.com"
  email = "karl.hepworth@gmail.com"
  facebook = "the.ugly.bum"
  googleplus = "100742823054089470521"
  github = "fubarhouse"
  gitlab = "fubarhouse"
  bitbucket = "fubarhouse"
  twitter = "fubarhouse"
  linkedin = "karl-hepworth-0a652350"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
